package mocks

import "github.com/stretchr/testify/mock"

import "github.com/google/go-github/github"

// RepositoriesService is an autogenerated mock type for the RepositoriesService type
type RepositoriesService struct {
	mock.Mock
}

// ListStatuses provides a mock function with given fields: owner, repo, ref, opt
func (_m *RepositoriesService) ListStatuses(owner string, repo string, ref string, opt *github.ListOptions) ([]*github.RepoStatus, *github.Response, error) {
	ret := _m.Called(owner, repo, ref, opt)

	var r0 []*github.RepoStatus
	if rf, ok := ret.Get(0).(func(string, string, string, *github.ListOptions) []*github.RepoStatus); ok {
		r0 = rf(owner, repo, ref, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.RepoStatus)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(string, string, string, *github.ListOptions) *github.Response); ok {
		r1 = rf(owner, repo, ref, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string, *github.ListOptions) error); ok {
		r2 = rf(owner, repo, ref, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
