package mocks

import gh "poule/gh"
import github "github.com/google/go-github/github"
import mock "github.com/stretchr/testify/mock"

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// Issues provides a mock function with given fields: query, opt
func (_m *SearchService) Issues(query string, opt *github.SearchOptions) (*github.IssuesSearchResult, *github.Response, error) {
	ret := _m.Called(query, opt)

	var r0 *github.IssuesSearchResult
	if rf, ok := ret.Get(0).(func(string, *github.SearchOptions) *github.IssuesSearchResult); ok {
		r0 = rf(query, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.IssuesSearchResult)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(string, *github.SearchOptions) *github.Response); ok {
		r1 = rf(query, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, *github.SearchOptions) error); ok {
		r2 = rf(query, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

var _ gh.SearchService = (*SearchService)(nil)
